AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - config/initializers/devise.rb
    - db/seeds.rb
    - db/schema.rb
  TargetRubyVersion: 
    2.3
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false
ClassLength:
  Max: 260
Metrics/MethodLength:
  CountComments: false
  Max: 25
Metrics/ModuleLength:
  CountComments: false
  Max: 200
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
FormatString:
  EnforcedStyle: sprintf
Rails/OutputSafety:
  Enabled: false
