AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - config/initializers/devise.rb
    - db/seeds.rb
    - db/schema.rb
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false
ClassLength:
  Max: 260
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 25
Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200
FormatString:
  EnforcedStyle: sprintf
Rails/OutputSafety:
  Enabled: false
