source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'passenger', '>= 5.0.30', require: 'phusion_passenger/rack_handler'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Some crazy, hot, luxury, vip and swag stuff from Twitter
gem 'bootstrap-sass', :git => 'https://github.com/twbs/bootstrap-sass.git', :branch => 'next'

# Let us use VK, bitcheeeez!
gem 'vkontakte_api', '~> 1.4'
gem 'koala', '~> 2.2' # Facebook API

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # gem 'byebug'
  # gem 'rspec-rails'
  gem 'nyan-cat-formatter'
  gem 'awesome_print'
  gem 'simplecov', require: false, group: :test
  gem 'spring-commands-rspec'
end

group :test do
  gem 'factory_girl_rails'
  gem 'faker'
  # gem 'simplecov'
  gem 'fuubar'
  gem 'shoulda-matchers',   '~> 3.1'
  # gem 'database_cleaner',   '~> 1.3.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-byebug'
end

# Devise for auth with vk, fb...
gem 'devise'
gem 'omniauth-facebook'
gem 'omniauth-vkontakte'
gem 'omniauth'
# Devise for auth with vk, fb...
