source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.18'
gem 'passenger', '>= 5.0.30', require: 'phusion_passenger/rack_handler'

gem 'uglifier', '>= 1.3.0'
gem 'bootstrap-sass', git: 'https://github.com/twbs/bootstrap-sass.git', branch: 'next'
gem 'bootswatch-rails'
gem 'jquery-rails'

gem 'simple_form'
gem 'gmaps4rails'
gem 'kaminari'

gem 'vkontakte_api', '~> 1.4'
gem 'koala', '~> 2.2' # Facebook API
gem 'devise'
gem 'omniauth-facebook'
gem 'omniauth-vkontakte'
gem 'omniauth'

gem 'whenever', require: false

# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'shoulda'
  gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'
  gem 'byebug', platform: :mri
  gem 'nyan-cat-formatter'
  gem 'awesome_print'
  gem 'simplecov', require: false, group: :test
  gem 'spring-commands-rspec'
end

group :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'fuubar'
  # gem 'database_cleaner', '~> 1.3.0'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-byebug'
end
