default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: lits
  password: lits

development:
  <<: *default
  database: lits

test:
  <<: *default
  database: lits_test

production:
  <<: *default
  database: lits
  username: lits
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
