development:
  fb_app_id: 207194596386777
  fb_secret_key: 6458c9feb552b306b2d25164bcbd8b2d
  vk_app_id: 5677646
  vk_secret_key: qSb6nCDDukTmtoFMIJHO
test:
  fb_app_id: 207194596386777
  fb_secret_key: 6458c9feb552b306b2d25164bcbd8b2d
  vk_app_id: 5677646
  vk_secret_key: qSb6nCDDukTmtoFMIJHO
production:
  fb_app_id:     <%= ENV["FB_APP_ID"] %>
  fb_secret_key: <%= ENV["FB_SECRET_KEY"] %>
  vk_app_id:     <%= ENV["VK_APP_ID"] %>
  vk_secret_key: <%= ENV["VK_SECRET_KEY"] %>
